#!/bin/sh
set -e
# Automatically added by dh_php5
if [ -e /usr/share/php5/php5-maintscript-helper ] ; then
    . /usr/share/php5/php5-maintscript-helper
    for conf in couchbase  ; do
        php5_invoke enmod ALL $conf || exit $?
    done
else
    for conf in couchbase  ; do
        php5enmod $conf
    done
fi
# End automatically added section
