#!/bin/sh
set -e
# Automatically added by dh_php5
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    if [ -e /usr/share/php5/php5-maintscript-helper ] ; then
	. /usr/share/php5/php5-maintscript-helper

	for conf in couchbase  ; do
	    php5_invoke dismod ALL $conf || exit $?
	done
    else
        if [ -x /usr/sbin/php5dismod ]; then
            for conf in couchbase  ; do
	        php5dismod $conf
	    done
        else
            echo "WARN: php5-common has been removed, you need to cleanup /etc/php5 yourself."
        fi
    fi
fi
# End automatically added section
